# Generated by Django 3.0.6 on 2020-06-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200605_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
    ]
